### ISSUE TITLE
Looking for a bit of help.

### ISSUE THREAD

**Issue by Infernoman** [benhj/CryptoStreamPP#1]
http://stackoverflow.com/questions/33979956/crypto-encoding-decoding-fails-on-linux
If you need anymore information just let me know !

**Comment by benhj** [comment]
Thanks for your interest in the project! Please use this space for specific questions rather than linking elsewhere. Also, if possible, please provide a minimalistic and compilable example / reproduction steps to exemplify the issue. Thanks -- I will close this issue if I don't hear back by the end of the day.
